#!/usr/bin/python3

import sys
from time import sleep
from quick2wire.gpio import Pin

pin = Pin(int(sys.argv[1]) if len(sys.argv) > 2 else 22, Pin.Out)

while True:
    print("on")
    pin.value = 1
    sleep(1)
    
    print("off")
    pin.value = 0
    sleep(1)
