#!/usr/bin/python3

import sys
from time import sleep
from quick2wire.gpio import Pin

pin = Pin(int(sys.argv[1]) if len(sys.argv) > 2 else 12, Pin.Out)

try:
    while True:
        pin.value = 1 - pin.value
        sleep(1)
except KeyboardInterrupt:
    pin.unexport()
