#!/usr/bin/env python3

import sys
from time import sleep
from quick2wire.gpio import GPIOPin, In, Out

led = GPIOPin(1, direction=Out)
button = GPIOPin(0, direction=In)

with led, button:
     while True:
          led.value = button.value
          sleep(0.1)
