#!/usr/bin/env python3

from itertools import cycle
from time import sleep
from quick2wire.gpio import pins, In, Out

button = pins.pin(0, direction=In)
led = pins.pin(1, direction=Out)

with button, led:
    print("ready")
    
    for v in cycle([1,0]):
        led.value = v * button.value
        sleep(0.5)
