#!/usr/bin/env python3

import sys
from time import sleep
from quick2wire.gpio import gpio_breakout, In, Out

led = gpio_breakout.pin(1, direction=Out)
button = gpio_breakout.pin(0, direction=In)

with led, button:
     while True:
          led.value = button.value
          sleep(0.1)
