#!/usr/bin/python3

import sys
import os
from select import epoll, EPOLLET, EPOLLIN, EPOLLOUT, EPOLLERR
from quick2wire.gpio import GPIOPin, Both, In, Out, exported

with exported(GPIOPin(0, direction=In, interrupt=Both)) as button, exported(GPIOPin(1, direction=Out)) as led:
     
    ep = epoll()
    ep.register(button, EPOLLET|EPOLLIN)
    
    while True:
        for fileno, event in ep.poll():
            if event & EPOLLIN: 
                led.value = button.value
            


