#!/usr/bin/python3

import sys
import os
from quick2wire.gpio import GPIOPin, Both, In, Out, exported
from quick2wire.selector import Selector, INPUT, EDGE

with closing(Selector()) as selector, \
     exported(GPIOPin(0, direction=In, interrupt=Both)) as button, \
     exported(GPIOPin(1, direction=Out)) as led:
    
    selector.add(button, INPUT, trigger=EDGE)
    while True:
        selector.wait()
        if selector.has_input:
            led.value = button.value



