#!/usr/bin/env python3

from quick2wire.i2c import I2CMaster, writing_bytes, reading_into
import time

address = 0x20
iodir_register = 0x00
gpio_register = 0x09

with I2CMaster() as master:    
    master.transaction(
        writing_bytes(address, iodir_register, 0xFF))

    buf = bytearray(1)
    
    while True:
        master.transaction(
            writing_bytes(address, gpio_register),
            reading_into(address, buf))
        
        print("%02x" % buf[0])
        
        time.sleep(1)
