#! /usr/bin/env python3
from quick2wire.parts.pcf8591 import *
from contextlib import closing
import quick2wire.i2c as i2c
from time import sleep

# Connect AOUT to Pin A1
if __name__ == '__main__':
    with closing(i2c.I2CMaster(0)) as master:
        pcf = PCF8591(master, 0x48)
        count = 1
        pin = pcf.begin_analoge_read(1)
        while True:
            pcf.analoge_out(count)
            data = pin.read()
            print("wrote: {}, read: {}".format(count,data))
            count += 1
            if count > 255:
                count = 0
            sleep(.5)

