#! /usr/bin/env python3
from quick2wire.parts.pcf8591 import *
from contextlib import closing
import quick2wire.i2c as i2c
from time import sleep

# Connect VREF to one end of a Pot, AGND to another, and Pin 0 to the wiper
if __name__ == '__main__':
    with closing(i2c.I2CMaster(0)) as master:
        pcf = PCF8591(master, 0x48)
        pcf.begin_analoge_in(0)
        count = 1
        while True:
            data = pcf.read(1)
            print("read: " + str(count) + ":" + str(data[0]))
            count += 1
            sleep(.5)

