#!/usr/bin/env python3

import sys
import os
from contextlib import closing
from quick2wire.gpio import pins, Both, In, Out
from quick2wire.selector import Selector, Timer

blink_rate=2.0

with pins.pin(0, direction=In, interrupt=Both) as button, \
     pins.pin(1, direction=Out) as led, \
     Timer(interval=1/blink_rate) as timer, \
     Selector() as selector:
    
    selector.add(button)
    selector.add(timer)
    
    print("ready")
    
    while True:
        selector.wait()
        
        if selector.ready == button:
            if button.value:
                led.value = 1
                timer.start()
            else:
                led.value = 0
                timer.stop()
        
        elif selector.ready == timer:
            timer.wait()
            led_pin.value = not led_pin.value
